### PR TITLE
Opt post fine tuning

### PR DESCRIPTION
**Pull request by ElStabilini**
First draft pull request for analysis of optimization post fine tuning (1 ramsey + 1flipping).
Reference baseline: https://github.com/ElStabilini/qw11q_calibration/blob/fine-tuning/runcard_cal/recalD1_for_opt/rb/new_platform/parameters.json

To do:
* compare fidelity results as function of step number
* plot fidelity surface as parameter function
* test nelder-mead with initial symplex
* test optuna

Investigate:
* Initialization is the same for all methods but the first optimization point in plots is in different region of parameter space for different optimization methods
* methods explore different regions of parameter space

Comparative plots can be seen at https://github.com/ElStabilini/optimization/blob/opt_post-fine-tuning/opt_analysis/compatibility.ipynb

@Edoardo-Pedicillo @alecandido @andrea-pasquale

### CODE REVIEW

**Comment by alecandido** [comment]
@ElStabilini, please, take into account #6 as soon as possible.

One of the reasons why PRs are useful is because they highlight the work done on top of the current state (i.e. the targeted branch, `main` for this PR), but with too many files GitHub is not even able to generate the diff

**Comment by alecandido** [comment]
Btw, it takes ~5m to clone, and it is almost 9 GiB of size on disk.

I'm still inspecting the content, but we may have to find a different solution even for the data (btw, GitHub has a hard limit on the file size).

<details><summary>Details</summary>
<p>

```nushell
----------- in ------------------
❯ : gh repo clone ElStabilini/optimization
Cloning into 'optimization'...
remote: Enumerating objects: 5802, done.
remote: Counting objects: 100% (592/592), done.
remote: Compressing objects: 100% (241/241), done.
Receiving objects: 100% (5802/5802), 2.39 GiB | 15.04 MiB/s, done.
remote: Total 5802 (delta 356), reused 575 (delta 350), pack-reused 5210 (from 1)
Resolving deltas: 100% (4260/4260), done.
Updating files: 100% (3113/3113), done.

----------- in ------------------ took 4m39s
❯ : du optimization/
╭───┬─────────────────────────────────────────────────┬──────────┬──────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────╮
│ # │                      path                       │ apparent │ physical │                                                        directories                                                         │ ... │
├───┼─────────────────────────────────────────────────┼──────────┼──────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────┤
│ 0 │ ----------------------------------/optimization │  8.7 GiB │  8.7 GiB │ ╭───┬───────────────────────────────────────────────────────────────────┬───────────┬───────────┬────────────────┬───────╮ │ ... │
│   │                                                 │          │          │ │ # │                               path                                │ apparent  │ physical  │  directories   │ files │ │     │
│   │                                                 │          │          │ ├───┼───────────────────────────────────────────────────────────────────┼───────────┼───────────┼────────────────┼───────┤ │     │
│   │                                                 │          │          │ │ 0 │ ----------------------------------/optimization/opt_analysis      │ 654.6 KiB │ 672.0 KiB │ [table 2 rows] │       │ │     │
│   │                                                 │          │          │ │ 1 │ ----------------------------------/optimization/optimization_test │ 128.9 MiB │ 129.1 MiB │ [table 3 rows] │       │ │     │
│   │                                                 │          │          │ │ 2 │ ----------------------------------/optimization/rb_opt            │   2.5 GiB │   2.5 GiB │ [table 3 rows] │       │ │     │
│   │                                                 │          │          │ │ 3 │ ----------------------------------/optimization/rb_opt3h_analysis │   4.8 MiB │   4.8 MiB │                │       │ │     │
│   │                                                 │          │          │ │ 4 │ ----------------------------------/optimization/__pycache__       │   2.4 KiB │   4.0 KiB │                │       │ │     │
│   │                                                 │          │          │ │ 5 │ ----------------------------------/optimization/rb_opt3h          │   2.1 GiB │   2.1 GiB │ [table 3 rows] │       │ │     │
│   │                                                 │          │          │ │ 6 │ ----------------------------------/optimization/.git              │   2.4 GiB │   2.4 GiB │ [table 4 rows] │       │ │     │
│   │                                                 │          │          │ │ 7 │ ----------------------------------/optimization/optimization_data │   1.6 GiB │   1.6 GiB │ [table 2 rows] │       │ │     │
│   │                                                 │          │          │ │ 8 │ ----------------------------------/optimization/opt_analysis_D1   │ 341.8 KiB │ 356.0 KiB │                │       │ │     │
│   │                                                 │          │          │ │ 9 │ ----------------------------------/optimization/rb_opt_analysis   │ 332.6 KiB │ 340.0 KiB │                │       │ │     │
│   │                                                 │          │          │ ╰───┴───────────────────────────────────────────────────────────────────┴───────────┴───────────┴────────────────┴───────╯ │     │
╰───┴─────────────────────────────────────────────────┴──────────┴──────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────╯

```

</p>
</details>

**Comment by ElStabilini** [comment]
I am trying to figure out how to store differently the data. I can definitely store them in another folder and not uploading them on GitHub. At this point I think I should also remove the ones I already have here do you have any suggestion on how to do it?

Probably to avoid storing all RB data it would be useful to directly call the rb methods instead of the whole routine?

**Comment by alecandido** [comment]
@ElStabilini before I didn't know exactly what was taking up space, and I was a bit confused myself.

When I found out that is the RB data, I believe there is an easy temporary solution.

In particular, in order to extract the RB fidelity (which is one float with its uncertainties, thus a pair of floats), you are acquiring a whole data set, for each length and many times for a certain length.
These data are e.g. in here:
https://github.com/ElStabilini/optimization/blob/opt_post-fine-tuning/optimization_data/D1_nelder-mead/data/rb_ondevice-42/data.npz
instead, the part you're consuming is just the following:
https://github.com/ElStabilini/optimization/blob/opt_post-fine-tuning/optimization_data/D1_nelder-mead/data/rb_ondevice-42/results.json
and even more specifically,
https://github.com/ElStabilini/optimization/blob/d0f687d0b412a1bc3ae1cda3118c8bafa49973a3/optimization_data/D1_nelder-mead/data/rb_ondevice-42/results.json#L212-L231
which are 12 floats (if you also take into account the values for A and B, and the full covmat).

So, for a 1e3 reduction in size (8 MB -> >~8 KB) you just need to delete (i.e. ignore) the `.npz` files inside the data folders (and that's something simple, that you can do just at the level of `.gitignore` - since it's very unlikely you will analyze again the raw data).

Instead, we can distill even more just by following #10 (that can happen at a later stage), and storing arrays for the parameters above (or even just for the fidelity and its uncertainty, i.e. the diagonal element in the covmat related to that parameter). This will give you a single "history" data file per optimization sequence, in a standard format - that part could be analyzed again offline to investigate what happen, and it's precious to store and share.

**Comment by alecandido** [comment]
Btw: the repo itself (the `.git/` folder top-level) now weights ~2.4 GiB, and that won't change by ignoring files.
Indeed, when you ignore something, that will happen "from now on" (also, you need to `git rm path/to/tracked/file` in order to stop tracking, and saving modifications, for files that you are already tracking - i.e. that are already in the repo - despite they now match a `.gitignore` rule).

Purging Git repos, i.e. the histories, is possible[*], but it's quite cumbersome. The moment the files will be ignored I will do that for you (or better, as soon as you will implement #10 - since it will make my life easier).
No need to hurry for that - you have all the files in your local repo, and it's not urgent that someone else will work on your same files. But better to be ready in advance ^^

[*]: and necessary, e.g. if you realize to be leaking secrets - such as password and tokens

**Pull request merged**
